config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|fr/ do
    get '/dashboard', to: 'pages#dashboard', as: 'pages_dashboard'
    resources :accessories
    resources :extractions
    resources :tastings
    resources :flavors, only: [:index, :show]
    resources :user_coffees
    resources :coffees
    resources :varieties, only: [:index, :show]
  end
  # Add other routes if necessary

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_coffees
  has_many :coffees, through: :user_coffees
  has_many :extractions
  has_many :tastings
  has_many :accessories
end

app/controllers/extractions_controller.rb
class ExtractionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_extraction, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:show, :edit, :update, :destroy]
  before_action :set_brewer_accessories, only: [:new, :edit, :create, :update]
  before_action :set_default_params, only: [:new, :edit]

  def index
    @extractions = current_user.extractions
  end

  def show
  end

  def new
    @extraction = current_user.extractions.build
  end

  def edit
  end

  def create
    @extraction = current_user.extractions.build(extraction_params)

    if @extraction.user_coffee_id.present?
      @extraction.coffee_id = UserCoffee.find(@extraction.user_coffee_id).coffee_id
    else
      flash.now[:alert] = 'Sorry, the extraction needs to be associated with a coffee.'
      render :new, status: :unprocessable_entity and return
    end

    if @extraction.brewing_method_id.present?
      @extraction.brewing_method_id = params[:extraction][:brewing_method_id]
    else
      flash.now[:alert] = 'Sorry, the extraction needs to be associated with a brewing method.'
      render :new, status: :unprocessable_entity and return
    end

    if params[:extraction][:grinder_id].present?
      @extraction.accessories << Accessory.find(params[:extraction][:grinder_id])
    end
    if @extraction.save
      redirect_to @extraction, notice: 'Extraction was successfully created.'
    else
      flash.now[:alert] = @extraction.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @extraction.update(extraction_params)
      if params[:extraction][:grinder_id].present?
        @extraction.accessories << Accessory.find(params[:extraction][:grinder_id])
      end
      redirect_to @extraction, notice: 'Extraction was successfully updated.'
    else
      render :edit, status: :unprocessable_entity, notice: 'Sorry Extraction was NOT updated.'
    end
  end

  def destroy
    if @extraction.destroy
      redirect_to extractions_url, notice: 'Extraction was successfully destroyed.'
    else
      redirect_to extractions_url, status: :unprocessable_entity, notice: 'Sorry, extraction was NOT destroyed.'
    end
  end

  private

  def set_extraction
    @extraction = Extraction.find(params[:id])
  end

  def extraction_params
    params.require(:extraction).permit(
      :brewing_method_id, :user_coffee_id, :weight_in,
      :weight_target, :water_temperature, :pre_infusion_time, :bloom_weight,
      :extraction_time, :weight_out, :comment, :grinder_set, :grinder_id, accessory_ids: []
    )
  end

  def authorize_user!
    redirect_to extractions_path, alert: 'Not authorized.' unless @extraction.user == current_user
  end

  def set_brewer_accessories
    required_types = [
      'Aero press',
      'Cold brew',
      'Drip coffee',
      'Espresso',
      'French press',
      'Moka Pot',
      'Pour-Over',
      'Siphon coffee',
      'Turkish coffee',
      'Vietnamese Phin'
    ]
    @brewer_accessories = current_user.accessories.where(accessory_type: required_types)
  end

  def set_default_params
    # Find the last extraction for the current user with the specified brewing method
    last_extraction = current_user.extractions.last

    # Define default values
    default_weight_in = 18
    default_weight_target = default_weight_in * 2
    default_brewing_method_id = current_user.accessories.brewing_method.last&.id
    default_water_temperature = 93
    default_pre_infusion_time = 8
    default_extraction_time = 20
    default_bloom_weight = default_weight_in * 2
    default_weight_out = default_weight_in * 2
    default_grinder_id = current_user.accessories.grinder.last&.id
    default_grinder_set = 3
    default_user_coffee_id = current_user.user_coffees.last&.id
    default_accessory_ids = last_extraction ? last_extraction.accessories.where.not(accessory_type: Accessory::BREWING_METHODS + ['Grinder']).pluck(:id) : []

    # Set default params based on last extraction or predefined default values
    @default_params = {
      weight_in: last_extraction&.weight_in || default_weight_in,
      weight_target: last_extraction&.weight_target || default_weight_target,
      brewing_method_id: last_extraction&.brewing_method_id || default_brewing_method_id,
      water_temperature: last_extraction&.water_temperature || default_water_temperature,
      pre_infusion_time: last_extraction&.pre_infusion_time || default_pre_infusion_time,
      extraction_time: last_extraction&.extraction_time || default_extraction_time,
      bloom_weight: last_extraction&.bloom_weight || default_bloom_weight,
      weight_out: last_extraction&.weight_out || default_weight_out,
      grinder_id: last_extraction&.accessories&.grinder&.last&.id || default_grinder_id,
      grinder_set: last_extraction&.grinder_set || default_grinder_set,
      user_coffee_id: last_extraction&.user_coffee_id || default_user_coffee_id,
      accessory_ids: default_accessory_ids
    }
  end
end

app/views/extractions/_form.html.erb
<%= simple_form_for(@extraction) do |f| %>
  <% @default_params ||= {} %>





  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to 'Back', extractions_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/extractions/edit.html.erb
<div class="new-acc-main-container">
  <%= simple_form_for(@extraction) do |f| %>
    <div class="field new-acc-flex-column-center-container">
      <h3>Edit Extraction</h3>

      <div class="extrac-new-acc-single">
        Coffee
        <div class="extrac-new-acc-tile"></div>
        <%= f.input :user_coffee_id,
                    collection: current_user.user_coffees, as: :select,
                    include_blank: true, label: false,
                    value_method: :id, input_html: { class: 'form-control', multiple: false } %>
      </div>

      <div>
        Grinder
        <div class="extrac-new-acc-tile"></div>
        <%= f.input :grinder_id,
                    collection: current_user.accessories.where(accessory_type: 'Grinder').pluck(:name, :id),
                    as: :select, include_blank: true, label: false,
                    input_html: { class: 'form-control', multiple: false } %>
      </div>

      <div>
        Brewer
        <div class="extrac-new-acc-tile"></div>
        <%= f.input :brewing_method_id,
                    collection: current_user.accessories.where(accessory_type: Accessory::BREWING_METHODS).pluck(:name, :id),
                    as: :select, include_blank: true, label: false,
                    input_html: { class: 'form-control', multiple: false } %>
      </div>

      <div>
        <%= f.input :grinder_set, input_html: { class: 'form-control' }, label: 'Grinder Setting' %>
      </div>

      <div>
        <%= f.input :weight_in, input_html: { class: 'form-control' }, label: 'Weight In' %>
      </div>

      <div>
        <%= f.input :weight_target, input_html: { class: 'form-control' }, label: 'Weight Target' %>
      </div>

      <div>
        <%= f.input :weight_out, input_html: { class: 'form-control' }, label: 'Weight Out' %>
      </div>

      <div>
        <%= f.input :water_temperature, input_html: { class: 'form-control' }, label: 'Water Temperature' %>
      </div>

      <div>
        <%= f.input :pre_infusion_time, input_html: { class: 'form-control' }, label: 'Pre-infusion Time' %>
      </div>

      <div>
        <%= f.input :bloom_weight, input_html: { class: 'form-control' }, label: 'Bloom Weight' %>
      </div>

      <div>
        <%= f.input :extraction_time, input_html: { class: 'form-control' }, label: 'Extraction Time' %>
      </div>

      <div>
        <%= f.input :comment, input_html: { class: 'form-control' }, label: 'Comments' %>
      </div>

      <div class="extrac-new-acc-secondary">
        <h4>Optional Accessories</h4>
        <%= f.input :accessory_ids,
                    collection: current_user.accessories.where.not(accessory_type: Accessory::BREWING_METHODS + ['Grinder']),
                    as: :check_boxes, label_method: :name, value_method: :id,
                    input_html: { class: 'form-check-input' },
                    item_wrapper_class: 'form-check' %>
      </div>
    </div>

    <div class="new-acc-actions-buttons">
      <%= link_to 'Back to Dashboard', pages_dashboard_path, class: 'btn btn-outline-secondary' %>
      <div class="btn btn-warning">
        <%= link_to 'Delete Extraction', @extraction, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-warning' %>
      </div>
      <%= f.button :submit, 'Update Extraction', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/extractions/index.html.erb
<%= link_to 'New Extraction', new_extraction_path, class: "btn btn-primary" %>
  <br>
  <br> <h1>My Extractions</h1>
<br>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Coffee</th>
      <th>Grinder</th>
      <th>Brewer</th>
      <th>Grinder Position</th>
      <th>Water Temperature</th>
      <th>Weight In</th>
      <th>Weight Target</th>
      <th>Weight Out</th>
      <th>Pre-infusion Time</th>
      <th>Bloom Weight</th>
      <th>Extraction Time</th>
      <th>Comments</th>
      <th>Accessories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @extractions.each do |extraction| %>
      <tr>
        <td><%= link_to 'Show', extraction, class: 'btn btn-secondary' %> <br>
        <%= link_to 'Destroy', extraction, class: 'btn btn-warning', data: { turbo_method: "delete", turbo_confirm: "Are you sure?" } %></td>
        <td><%= extraction.brewing_method.name %></td>
        <td><%= extraction.user_coffee.name%></td>
        <td><%= extraction.accessories.find_by(accessory_type: 'Grinder')&.name %></td>
        <td><%= extraction.grinder_set %></td>
        <td><%= extraction.water_temperature %></td>
        <td><%= extraction.weight_in %></td>
        <td><%= extraction.weight_target %></td>
        <td><%= extraction.weight_out %></td>
        <td><%= extraction.pre_infusion_time %></td>
        <td><%= extraction.bloom_weight %></td>
        <td><%= extraction.extraction_time %></td>
        <td><%= extraction.comment %></td>
        <td><%= extraction.accessories.where.not(accessory_type: 'Grinder').map(&:name).join(', ') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/extractions/new.html.erb
<%= simple_form_for(@extraction) do |f| %>
<div class= "extrac-new-main-container">
  <div class="actions-buttons">
    <%= link_to 'Back', 'javascript:history.back()', class: 'btn btn-outline-secondary', onclick: "if (document.referrer === '') { window.location.href = '#{pages_dashboard_path}'; }" %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
  <h1>New Extraction</h1>

  <% @default_params ||= {} %>

    <div class="extrac-new-step">
      <div class="extrac-new-acc-container">
        <div class="extrac-new-acc-single">
          Coffee
          <div class="extrac-new-acc-tile">
          </div>
          <%= f.input :user_coffee_id,
              collection: current_user.user_coffees.where(archived: [false, nil]), as: :select,
              include_blank: true,
              value_method: :id,
              label: false,
              label_method: :coffee_details,
              selected: @default_params[:user_coffee_id],
              input_html: { class: 'form-control', multiple: false }%>
        </div>
          <div>
            Grinder
            <div class="extrac-new-acc-tile">
            </div>
            <%= f.input :grinder_id,
                collection: current_user.accessories.grinder, as: :select,
                include_blank: true,
                label: false,
                value_method: :id,
                label_method: :name,
                selected: @default_params[:grinder_id],
                input_html: { class: 'form-control', multiple: false } %>
                <%= f.input :grinder_set, label: "Grinder Position", input_html: { class: 'form-control', value: @default_params[:grinder_set] } %>
          </div>
        <div>
          Brewer
          <div class="extrac-new-acc-tile">
          </div>
          <%= f.input :brewing_method_id,
                collection: current_user.accessories.brewing_method.pluck(:name, :id),
                label: false,
                selected: @default_params[:brewing_method_id],
                input_html: { class: 'form-control' } %>
          <%= f.input :water_temperature, label: "Water Temperature", input_html: { class: 'form-control', value: @default_params[:water_temperature] } %>
        </div>
      </div>

      <div class="extrac-new-acc-secondary">
        <h4>Optional Accessories</h4>
        <%= f.input :accessory_ids,
                    collection: current_user.accessories.optionals,
                    as: :check_boxes,
                    label_method: :name,
                    value_method: :id,
                    input_html: { class: 'form-check-input' },
                    item_wrapper_class: 'form-check',
                    checked: @default_params[:accessory_ids] %>
      </div>

      <br>

      <div class="">
        <h4>dials before</h4>
        <%= f.input :weight_in, label: "Weight In", input_html: { class: 'form-control', value: @default_params[:weight_in] } %>
        <%= f.input :weight_target, label: "Weight Target", input_html: { class: 'form-control', value: @default_params[:weight_target] } %>
        <br>
      </div>

      <%# <div class="">
        <h4>optional accessories</h4>
        espresso paper filter <br>
        WDT<br>
        Distributor<br>
        <br>
      </div> %>

      <div class="">
        <%= f.input :comment, as: :text, label: "Comment", input_html: { class: 'form-control', value: @default_params[:comment] } %>
      </div>
    </div>

  </div>

    <div class="extrac-new-step">
      TIMER <br>
      <br>
      Timer start - Timer reset - Timer preinfusion/bloom end - Timer stop
      <br>
    </div>

    <div class="extrac-new-step">
      <div class="extrac-new-dials-after">
        <h4>dials after</h4>
        <%= f.input :pre_infusion_time, label: "Pre-infusion Time", input_html: { class: 'form-control', value: @default_params[:pre_infusion_time] } %>
        <%= f.input :bloom_weight, label: "Bloom Weight", input_html: { class: 'form-control', value: @default_params[:bloom_weight] } %>
        <%= f.input :extraction_time, label: "Extraction Time", input_html: { class: 'form-control', value: @default_params[:extraction_time] } %>
        <%= f.input :weight_out, label: "Weight Out", input_html: { class: 'form-control', value: @default_params[:weight_out] } %>
        <br>
      </div>
    </div>


    <%= f.button :submit, class: 'btn btn-primary' %>

 <% end %>

<br>
  <br>

    <div class="extrac-new-step">
      <div class="extrac-new-tasting">
        <h4>Tasting</h4>
        Global rating slider<br>

        <br>
        fragrance slider<br>
        acidity slider<br>
        flavor slider<br>
        body slider<br>
        aftertaste slider<br>
        balance slider<br>
        <br>
        flavors list tool or link<br>
        <br>
        comments<br>
      </div>
    </div>

</div>

app/views/extractions/show.html.erb
<div class="actions-buttons">
  <%= link_to 'Back', extractions_path, class: 'btn btn-outline-secondary' %>
  <%= link_to 'Edit', edit_extraction_path(@extraction), class: 'btn btn-secondary' %>
  <%= link_to 'Destroy', @extraction, class: 'btn btn-warning', data: { turbo_method: "delete", turbo_confirm: "Are you sure?" } %>
</div>

<p>
  <strong>Coffee:</strong>
   <%= @extraction&.user_coffee&.coffee_details %>
</p>

<p>
  <strong>Grinder:</strong>
  <%= @extraction.accessories.grinder.first.name %>
</p>

<p>
  <strong>Brewing Method:</strong>
  <%= @extraction.brewing_method.name %>
</p>

<p>
  <strong>Grinder Setting:</strong>
  <%= @extraction.grinder_set %>
</p>

<p>
  <strong>Water Temperature:</strong>
  <%= @extraction.water_temperature %>
</p>

<p>
  <strong>Weight In:</strong>
  <%= @extraction.weight_in %>
</p>

<p>
  <strong>Weight Target:</strong>
  <%= @extraction.weight_target %>
</p>

<p>
  <strong>Weight Out:</strong>
  <%= @extraction.weight_out %>
</p>

<p>
  <strong>Pre-infusion Time:</strong>
  <%= @extraction.pre_infusion_time %>
</p>

<p>
  <strong>Bloom Weight:</strong>
  <%= @extraction.bloom_weight %>
</p>

<p>
  <strong>Extraction Time:</strong>
  <%= @extraction.extraction_time %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @extraction.comment %>
</p>

<p>
  <strong>Accessories:</strong>
  <%= @extraction.accessories.where.not(accessory_type: 'Grinder').map(&:name).join(', ') %>
</p>