config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|fr/ do
    get '/dashboard', to: 'pages#dashboard', as: 'pages_dashboard'
    resources :accessories
    resources :extractions
    resources :tastings
    resources :flavors, only: [:index, :show]
    resources :user_coffees
    resources :coffees
    resources :varieties, only: [:index, :show]
  end
  # Add other routes if necessary

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-top">
  <div>
    <% if user_signed_in? %>
      <%= link_to pages_dashboard_path, class: "nav-link" do %>
        <i class="fa-solid fa-house"></i>
      <% end %>
    <% end %>
  </div>

  <div><h4 class="navbar-app-name">Coffee Tree</h4></div>

  <div>
    <% if user_signed_in? %>
      <div class="nav-item dropdown">
        <a href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa-solid fa-bars"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "Dashboard", pages_dashboard_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="navbar-bottom">
  <%= link_to accessories_path, class: "navbar-bottom-item" do %>
    <p><%= t(:toys) %></p>
    <i class="fa-solid fa-kitchen-set"></i>
  <% end %>
  <%= link_to user_coffees_path, class: "navbar-bottom-item" do %>
    <p><%= t(:beans) %></p>
    <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 22 22" style="fill: rgba(222, 184, 135, 1);transform: ;msFilter:;"><path d="M6 18a6.06 6.06 0 0 0 5.17-6 7.62 7.62 0 0 1 6.52-7.51l2.59-.37c-.07-.08-.13-.16-.21-.24-3.26-3.26-9.52-2.28-14 2.18C2.28 9.9 1 15 2.76 18.46z"></path><path d="M12.73 12a7.63 7.63 0 0 1-6.51 7.52l-2.46.35.15.17c3.26 3.26 9.52 2.29 14-2.17C21.68 14.11 23 9 21.25 5.59l-3.34.48A6.05 6.05 0 0 0 12.73 12z"></path></svg>
  <% end %>

  <%= link_to extractions_path, class: "navbar-bottom-item" do %>
    <p><%= t(:brews) %></p>
    <i class="fa-solid fa-mug-hot"></i>
  <% end %>
  <%= link_to pages_dashboard_path, class: "navbar-bottom-item" do %>
    <p><%= t(:dashboard_short) %></p>
    <i class="fa-solid fa-table-columns"></i>
  <% end %>
</div>