config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|fr/ do
    get '/dashboard', to: 'pages#dashboard', as: 'pages_dashboard'
    resources :accessories
    resources :extractions
    resources :tastings
    resources :flavors, only: [:index, :show]
    resources :user_coffees
    resources :coffees
    resources :varieties, only: [:index, :show]
  end
  # Add other routes if necessary

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/dashboard.html.erb
<div class="container mt-5">
  <h1><%= t('.dashboard') %></h1>

  <!-- Extractions Section -->
  <div class="card mt-4">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h2><%= t('.recent_extractions') %></h2>
      <div>
        <%= link_to t('.new'), new_extraction_path, class: 'btn btn-primary mx-1' %>
        <%= link_to t('.view_all'), extractions_path, class: 'btn btn-secondary mx-1' %>
      </div>
    </div>
    <div class="card-body">
      <% if @extractions.present? %>
        <ul class="list-group">
          <% @extractions.each do |extraction| %>
            <li class="list-group-item">
              <strong><%= t('method') %>:</strong> <%= extraction.brewing_method.name %> |
              <strong><%= t(:date) %>:</strong> <%= l(extraction.created_at, format: :short) %>
              <p><%= extraction.comment %></p>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p><%= t('.no_extractions_found') %></p>
      <% end %>
    </div>
  </div>

  <!-- User Coffees Section -->
  <div class="card mt-4">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h2><%= t('.recent_coffees') %></h2>
      <div>
        <%= link_to t('.new'), new_user_coffee_path, class: 'btn btn-primary mx-1' %>
        <%= link_to t('.view_all'), user_coffees_path, class: 'btn btn-secondary mx-1' %>
      </div>
    </div>
    <div class="card-body">
      <% if @user_coffees.present? %>
        <ul class="list-group">
          <% @user_coffees.each do |coffee| %>
            <li class="list-group-item">
              <strong><%= t(:name) %>:</strong> <%= coffee.coffee.name %> |
              <strong><%= t(:weight_left) %>:</strong> <%= coffee.weight_left %>g
              <p><%= coffee.personal_notes %></p>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p><%= t('.no_coffees_found') %></p>
      <% end %>
    </div>
  </div>

  <!-- Accessories Section -->
<div class="card mt-4">
  <div class="card-header d-flex justify-content-between align-items-center">
    <h2><%= t('.accessories') %></h2>
    <div>
      <%= link_to t('.new'), new_accessory_path, class: 'btn btn-primary mx-1' %>
      <%= link_to t('.view_all'), accessories_path, class: 'btn btn-secondary mx-1' %>
    </div>
  </div>
  <div class="card-body">
    <!-- Brewing Methods Section -->
    <h3><%= t('.last_3_brewing_methods') %></h3>
    <% if @brewing_methods.present? %>
      <ul class="list-group mb-4">
        <% @brewing_methods.each do |accessory| %>
          <li class="list-group-item">
            <strong><%= accessory.name %></strong> | <%= accessory.accessory_type %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p><%= t('.no_brewing_methods_found') %></p>
    <% end %>

    <!-- Other Accessories Section -->
    <h3><%= t('.last_5_accessories') %></h3>
    <% if @other_accessories.present? %>
      <ul class="list-group">
        <% @other_accessories.each do |accessory| %>
          <li class="list-group-item">
            <strong><%= accessory.name %></strong> | <%= accessory.accessory_type %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p><%= t('.no_other_accessories_found') %></p>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-welcome-message">
  <h1>Welcome to the CoffeeTree App</h1>
  <p>It seems you are not logged in.</p>
  <p>Please log in or create an account.</p>
  <div class="home-buttons-container">
    <%= link_to 'Log In', new_user_session_path, class: 'btn btn-primary' %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-secondary' %>
  </div>
</div>