config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|fr/ do
    get '/dashboard', to: 'pages#dashboard', as: 'pages_dashboard'
    resources :accessories
    resources :extractions
    resources :tastings
    resources :flavors, only: [:index, :show]
    resources :user_coffees
    resources :coffees
    resources :varieties, only: [:index, :show]
  end
  # Add other routes if necessary

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  BREWING_METHODS = [
    'Aero press',
    'Cold brew',
    'Drip coffee',
    'Espresso',
    'French press',
    'Moka Pot',
    'Pour-Over',
    'Siphon coffee',
    'Turkish coffee',
    'Vietnamese Phin'
  ]

  ACCESSORY_TYPES = [
    'Grinder',
    'Scale',
    'Basket',
    'Tamper',
    'Filter',
    'Kettle',
    'Distribution Tool',
    'Other'
  ] + BREWING_METHODS

  belongs_to :user

  has_and_belongs_to_many :extractions

  validates :name, presence: true
  validates :accessory_type, presence: true
  validates :grinder_min, presence: true, if: -> { accessory_type == 'Grinder' }
  validates :grinder_max, presence: true, if: -> { accessory_type == 'Grinder' }

  before_save :ensure_single_default

  scope :brewing_method, -> { where(accessory_type: Accessory::BREWING_METHODS) }
  scope :grinder, -> { where(accessory_type: 'Grinder') }
  scope :optionals, -> { where(accessory_type: ['Scale', 'Basket', 'Tamper', 'Filter', 'Kettle', 'Distribution Tool', 'Other']) }
  scope :scale, -> { where(accessory_type: 'Scale') }
  scope :basket, -> { where(accessory_type: 'Basket') }
  scope :tamper, -> { where(accessory_type: 'Tamper') }
  scope :filtering, -> { where(accessory_type: 'Filter') }
  scope :kettle, -> { where(accessory_type: 'Kettle') }
  scope :distribution_tool, -> { where(accessory_type: 'Distribution Tool') }
  scope :other, -> { where(accessory_type: 'Other') }

  def self.image_path(type)
    "accessories/#{type.parameterize(separator: '_')}_small.png"
  end

  private

  def ensure_single_default
    if self.default
      # Unset default for accessories of the same type
      Accessory.where(user_id: self.user_id, accessory_type: self.accessory_type, default: true).where.not(id: self.id).update_all(default: false)

      # Unset default for other brewing methods
      if BREWING_METHODS.include?(self.accessory_type)
        Accessory.where(user_id: self.user_id, accessory_type: BREWING_METHODS, default: true).where.not(id: self.id).update_all(default: false)
      end
    end
  end
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_accessory, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:show, :edit, :update, :destroy]

  def index
    @accessories = current_user.accessories
    @brewing_methods = current_user.accessories.where(accessory_type: Accessory::BREWING_METHODS).reverse
    @other_accessories = current_user.accessories.where.not(accessory_type: Accessory::BREWING_METHODS).reverse
  end

  def show
  end

  def new
    @accessory = Accessory.new
  end

  def edit
  end

  def create
    @accessory = current_user.accessories.build(accessory_params)
    @accessory.grinder_min = 0 # Setting default grinder min value as the DB require
    if @accessory.save
      redirect_to accessories_path, notice: 'Accessory was successfully created.'
    else
      redirect_to accessories_path, notice: 'Sorry the accessory FAILED to be created.'
    end
  end

  def update
    if @accessory.update(accessory_params)
      redirect_to accessory_path, notice: 'Accessory was successfully updated.'
    else
      render :edit, status: :unprocessable_entity, notice: 'Sorry the accessory FAILED to be created.'
    end
  end

  def destroy
    if @accessory.destroy
      redirect_to accessories_url, notice: 'Accessory was successfully destroyed.'
    else
      render :edit, status: :unprocessable_entity, notice: 'Sorry the accessory FAILED to be created.'
    end
  end

  private

  def set_accessory
    @accessory = Accessory.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to accessories_path, alert: 'Accessory not found.'
  end

  def authorize_user!
    redirect_to accessories_path, alert: 'You are not authorized.' unless @accessory.user == current_user
  end

  def accessory_params
    params.require(:accessory).permit(:name, :accessory_type, :comments, :grinder_max, :image_path)
  end
end

app/views/accessories/edit.html.erb
<div class="acc-edit-main-container">

  <div class="actions-buttons">
      <%= form_with model: @accessory, url: accessory_path(@accessory), method: :delete, data: { turbo_confirm: 'Êtes-vous sûr?' } do %>
        <%= button_tag 'Delete', class: 'btn btn-warning' %>
      <% end %>
    </div>

  <%= simple_form_for(@accessory) do |f| %>
    <div class="acc-flex-column-center-container">
      <h3><%= @accessory.name %></h3>

      <%= image_tag Accessory.image_path(@accessory.accessory_type), alt: @accessory.name, class: 'accessory-image' %>

      <div class="form-group">
        <%= f.input :name, label: "Name", input_html: { class: 'form-control' } %>
      </div>

      <% if @accessory.accessory_type == "Grinder" %>
        <%= f.input :grinder_max, label: "Max Setting" %>
      <% end %>

      <%= f.input :comments, label: "Comments", as: :text, input_html: { class: 'form-control' } %>

      <div class="actions-buttons">
        <%= link_to 'Back', 'javascript:history.back()', class: 'btn btn-outline-secondary', onclick: "if (document.referrer === '') { window.location.href = '#{pages_dashboard_path}'; }" %>
        <%= f.button :submit, 'Update', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/accessories/index.html.erb
<div class="acc-index-main-container">
  <h1><%= t('.accessories_of', username: current_user.nickname) %></h1>
  <div class="acc-index-actions-buttons">
    <%= link_to t(:back), pages_dashboard_path, class: 'btn btn-outline-secondary' %>
    <%= link_to t(:add_new), new_accessory_path, class: 'btn btn-primary' %>
  </div>

  <div class="acc-index-list">
    <!-- Brewing Methods Section -->
    <div class="acc-index-section">
      <h4><%= t('.brewing_methods') %></h4>
      <% @brewing_methods.each do |accessory| %>
        <div class="acc-index-item-wrapper">
          <%= link_to accessory_path(accessory), class: "acc-index-item" do %>
            <%= image_tag Accessory.image_path(accessory.accessory_type), alt: accessory.name, class: 'acc-index-image' %>
            <div class="acc-index-item-content">
              <h4><%= accessory.name %></h4>
              <p><%= t('.type') %>: <%= accessory.accessory_type %></p>
              <% if accessory.accessory_type == 'Grinder' %>
                <p>Grinder Range: <%= accessory.grinder_min %> - <%= accessory.grinder_max %></p>
              <% end %>
              <p><%= accessory.comments %></p>
            </div>
          <% end %>
          <div class="acc-index-delete-button">
            <%= link_to  accessory_path(accessory), data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr?"} do %>
              <i class="fa-solid fa-xmark"></i>
            <% end %>
          </div>
      <% end %>
    </div>

    <!-- Other Accessories Section -->
    <div class="acc-index-section">
      <h4><%= t('.other_accessories') %></h4>
      <% @other_accessories.each do |accessory| %>
        <div class="acc-index-item-wrapper">
          <%= link_to accessory_path(accessory), class: "acc-index-item" do %>
            <%= image_tag Accessory.image_path(accessory.accessory_type), alt: accessory.name, class: 'acc-index-image' %>
            <div class="acc-index-item-content">
              <h4><%= accessory.name %></h4>
              <p>Type: <%= accessory.accessory_type %></p>
              <% if accessory.accessory_type == 'Grinder' %>
                <p><%= t('.grinder_range') %>: <%= accessory.grinder_min %> - <%= accessory.grinder_max %></p>
              <% end %>
              <p><%= accessory.comments %></p>
            </div>
          <% end %>
          <div class="acc-index-delete-button">
            <%= link_to  accessory_path(accessory), data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr?"} do %>
              <i class="fa-solid fa-xmark"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/accessories/new.html.erb
<div class="new-acc-main-container">
  <%= simple_form_for @accessory, html: { data: { controller: "accessory" } } do |f| %>
    <div class="field acc-flex-column-center-container">
      <h3><%= t('.which_kind_accessory') %></h3>
      <div class="new-acc-main-btn-container" data-accessory-target="buttonGroup">
        <%= button_tag(type: 'button', class: 'new-acc-main-button', data: { action: "click->accessory#showBrewingMethods", accessory_target: "brewingButton" }) do %>
          <%= image_tag "accessories/brewing_method.png", alt: "Brewing Method" %>
        <% end %>
        <%= button_tag(type: 'button', class: 'new-acc-main-button', data: { action: "click->accessory#showOtherAccessories", accessory_target: "otherButton" }) do %>
          <%= image_tag "accessories/other_accessory.png", alt: "Other Accessory" %>
        <% end %>
      </div>
    </div>

    <div class="field acc-flex-column-center-container" data-accessory-target="brewingMethods" style="display: none;">
      <h4><%= t('.brewing_methods') %></h4>
      <div class="new-acc-type-selection">
        <% Accessory::BREWING_METHODS.each do |type| %>
          <%= image_tag "accessories/#{type.parameterize(separator: '_')}_small.png", alt: type, data: { action: "click->accessory#select", accessory_target: "accessoryImage", type: type } %>
        <% end %>
      </div>
    </div>

    <div class="field acc-flex-column-center-container" data-accessory-target="otherAccessories" style="display: none;">
      <h4><%= t('.other_accessories') %></h4>
      <div class="new-acc-type-selection">
        <% Accessory::ACCESSORY_TYPES.reject { |type| Accessory::BREWING_METHODS.include?(type) }.each do |type| %>
          <%= image_tag "accessories/#{type.parameterize(separator: '_')}_small.png", alt: type, data: { action: "click->accessory#select", accessory_target: "accessoryImage", type: type } %>
        <% end %>
      </div>
    </div>

    <%= f.hidden_field :accessory_type, id: "accessory_type", data: { accessory_target: "accessoryType" } %>

    <div class="acc-flex-column-center-container">
      <div class="field" style="display: none;" data-accessory-target="namefield">
        <%= f.label :name, t('.give_accessory_name') %>
        <%= f.input :name, label: false, input_html: { data: { accessory_target: "name" } } %>
      </div>

      <div style="display: none;" data-accessory-target="grinderField">
        <div class="new-acc-grinder-field_single">
          <%= f.input :grinder_min, label: false, input_html: { value: 0, class: 'new-acc-prefilled-input', style: "display: none;"} %>
          <%= f.label :grinder_max, t('.grinder_max_position') %>
          <div class="new-acc-grinder-field">
            <div>
              <%= button_tag(type: 'button', class: 'btn btn-secondary btn-minus-round', data: { action: "click->accessory#decrementMax", target: "accessory.grinderMaxButton" }) do %>
                <i class="fas fa-minus"></i>
              <% end %>
            </div>
            <%= f.input :grinder_max, label: false, input_html: { value: 30, placeholder: '30', class: 'new-acc-prefilled-input', data: { accessory_target: "grinderMaxInput" } } %>
            <div>
              <%= button_tag(type: 'button', class: 'btn btn-primary btn-plus-round', data: { action: "click->accessory#incrementMax", target: "accessory.grinderMaxButton" }) do %>
                <i class="fas fa-plus"></i>
              <% end %>
            </div>
          </div>
        </div>
    </div>

    <div class="field" style="display: none;" data-accessory-target="commentsField">
      <%= f.input :comments, label: t('.comments'), input_html: { data: { accessory_target: "comments" } } %>
    </div>


    <div class="actions-buttons">
      <%= link_to t(:back), 'javascript:history.back()', class: 'btn btn-outline-secondary', onclick: "if (document.referrer === '') { window.location.href = '#{pages_dashboard_path}'; }" %>
      <%= f.submit t('.add_accessory'), class: 'btn btn-primary', style: "display: none;", data: { accessory_target: "createButton" } %>
    </div>

  <% end %>
</div>

app/views/accessories/show.html.erb
<div class="new-acc-main-container">
  <div class="actions-buttons">
    <%= form_with model: @accessory, url: accessory_path(@accessory), method: :delete, data: { turbo_confirm: 'Êtes-vous sûr?' } do %>
      <%= button_tag t(:delete), class: 'btn btn-warning' %>
    <% end %>
    <%= link_to edit_accessory_path(@accessory), class: "btn btn-outline-primary" do %>
      <i class="fa-solid fa-pen-to-square"></i>
    <% end %>
  </div>
  <div class="field acc-flex-column-center-container">
    <h3><%= @accessory.name %></h3><%= image_tag Accessory.image_path(@accessory.accessory_type), alt: @accessory.name, class: 'acc-show-accessory-image' %>
    <p><%= t(:type) %> : <%= @accessory.accessory_type %></p>
    <% if @accessory.accessory_type == "Grinder"%>
      <p><%= t('.grinder_range') %> : <%= @accessory.grinder_min %> - <%= @accessory.grinder_max %> </p>
    <% end %>
    <%= @accessory.comments %>
  </div>

  <div class="actions-buttons">
    <%= link_to t(:back), 'javascript:history.back()', class: 'btn btn-outline-secondary', onclick: "if (document.referrer === '') { window.location.href = '#{pages_dashboard_path}'; }" %>
  </div>
</div>